name: "Code Scanning - Action"

on:
  push:
    branches: [master]
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Look for datadog configuration file
        run: |
          ls -lash
          FILE=src/datadog-rum.js
          if [ -f "$FILE" ]; then 
            echo "$FILE exists." 
          else 
            echo "$FILE doesn't exists."
            exit 1  
          fi

      - name: Look for import
        run: |
          ls -lash
          grep -r "import { datadogRum } from '@datadog/browser-rum';" ./*
