name: "Code Scanning - Action"

on:
  push:
    branches: [master]
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Look for import
        run: |
          ls -lash
          grep -r "import { datadogRum } from '@datadog/browserx-rum';" ./*
